server:
  port: 10623

spring:
  application:
    name: gtxsdemoxa
  datasource:
    url: jdbc:mysql://103.196.65.67:13306/db01?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 327604_Zcq
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.example.gtxs.xa.pojo
  cofig-location: classpath*:mybatis/mabatis-controller.xml
  mapper-locations: classpath*:mybatis/mapper/*.xml

test:
  datasource:
    url: jdbc:mysql://103.196.65.67:13306/db01?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 327604_Zcq
    driver-class-name: com.mysql.jdbc.Driver

gtxs:
  client:
    txGroupId: bee0e496-6101-4d34-886f-7973d8af7b26
  server:
    address: gtxs-server-cust56.netease.com:9627
  message:
    local: true
  service:
    disable: false
#  logging:
#    level: debug